Feat: Added chat screen and made necessary changes
kalviumcommunity/TherapEase pull request #5
Opened 2023-05-15 13:22 UTC by Ahamed1846

Added a new chat screen to the application and made some necessary changes to the code.

2023-05-16 03:51 UTC, jithin-kalvian requested changes
Please add the review changes

2023-05-16 03:51 UTC, jithin-kalvian commented on FrontEnd/src/Pages/ChatPage.jsx
There seems to be no error handling mechanism in place. For instance, what happens if ChatMock[index] or ChatMock[selectedCardIndex].messages is undefined? Consider adding safeguards for these situations.

2023-05-16 03:51 UTC, jithin-kalvian commented on FrontEnd/src/Pages/TherapistListingPage.jsx
> +              isLoggedIn={true}
add a todo comment here to indicate that this will be changed once the backend integration is complete

2023-05-16 04:49 UTC, Ahamed1846 commented on FrontEnd/src/Pages/ChatPage.jsx
Noted! Will do once backend integration is complete.

2023-05-16 05:38 UTC, yash0212 approved these changes
LGTM

2023-05-17 01:57 UTC, jithin-kalvian approved these changes
LGTM

2023-05-17 01:57 UTC, merged